name: Raid
version: 1.0.0
main: me.amogus360.raid.Raid
api-version: 1.20
load: startup
commands:
  raid:
    description: Command for raids
    usage: /raid <subcommand>
    aliases: [r]
  faction:
    description: Main command for factions
    usage: /raid <subcommand>
    aliases: [ r ]
  money:
    description: Main command for money
    usage: /raid <subcommand>
    aliases: [ r ]



