name: Raid
version: 1.0.0
main: me.amogus360.raid.Raid
api-version: 1.20
load: startup
commands:
  raid:
    description: Command for raids
    usage: /raid <subcommand>
    aliases: [r]
  faction:
    description: Main command for factions
    usage: /faction <subcommand>
    aliases: [r]
  money:
    description: Main command for money
    usage: /money <subcommand>
    aliases: [r]
  land:
    description: Main command for land
    usage: /land <subcommand>
    aliases: [r]
  item:
    description: Main command for item
    usage: /item <subcommand>
    aliases: [r]
  invite:
    description: Main command for invite
    usage: /invite <subcommand>
    aliases: [r]
  spawn:
    description: Teleport to spawn
    usage: /spawn
    aliases: [r]
  setspawn:
    description: Set spawn location
    usage: /setspawn
    aliases: [r]
  wildtp:
    description: Teleport to a random location in the wild
    usage: /wildtp
    aliases: [r]
permissions:
  factionsrevived:
    description: Factions Revived permissions
  factionsrevived.raid:
    description: Raid permissions
    children:
      factionsrevived.raid.mob:
        description: Allows players to summon a raid boss of their faction
        default: false
      factionsrevived.raid.join:
        description: Allows players to join a raid
        default: true
      factionsrevived.raid.start:
        description: Allows players to start a raid
        default: true
  factionsrevived.money:
    description: Money-related permissions
    children:
      factionsrevived.money.add:
        description: Allows players to give players money
        default: false
      factionsrevived.money.show:
        description: Allows players to show their money status
        default: true
      factionsrevived.money.send:
        description: Allows players to transfer money to different players
        default: true
  factionsrevived.faction:
    description: Faction-related permissions
    children:
      factionsrevived.faction.create:
        description: Allows you to create a faction
        default: true
      factionsrevived.faction.info:
        description: Gets the info of the faction
        default: true
      factionsrevived.faction.leave:
        description: Allows a player to leave a faction
        default: true
      factionsrevived.faction.delete:
        description: Deletes a faction
        default: true
      factionsrevived.faction.setspawn:
        description: Sets the faction's spawn location
        default: true
      factionsrevived.faction.setbosslocation:
        description: Sets the location of the faction's boss
        default: true
      factionsrevived.faction.spawn:
        description: Teleports to the faction's spawn
        default: true
  factionsrevived.item:
    description: Item-related permissions
    children:
      factionsrevived.item.shop:
        description: Allows users to open the item shop
        default: true
      factionsrevived.item.enhance:
        description: Allows users to open the item enhance gui
        default: true
  factionsrevived.invite:
    description: Invite-related permissions
    children:
      factionsrevived.invite.send:
        description: Sends an invitation to a player
        default: true
      factionsrevived.invite.accept:
        description: Accepts an invitation to a faction
        default: true
      factionsrevived.invite.show:
        description: Shows a list of pending invitations
        default: true
  factionsrevived.land:
    description: Land-related permissions
    children:
      factionsrevived.land.claim:
        description: Allows users to claim land
        default: true
      factionsrevived.land.show:
        description: Allows users to show land claims
        default: true
  factionsrevived.spawn:
    description: Teleport to spawn
    default: true
  factionsrevived.setspawn:
    description: Set spawn
    default: false
  factionsrevived.wildtp:
    description: Teleport to a random location in the wild
    default: true
